package io.selimdawa.bubblebottom

enum class AnimationMode {
    SLIDE, MORPH, BOUNCE, DROP, JUMP, FLIP, ZOOM, ROTATE, SHAKE, ANTICIPATE, ELASTIC, FADE, SQUASH, WAVE, PULSE, FLING, SPIN_MOVE, GLOW, JELLY, TILT
}